// this required method gives us the number of images in the folder number starts from 2 (at least according to this folder structure)
export const savedImages = {
  user: require('../assets/images/user.png'),
  blankFaceLp: require('../assets/images/albums/blank-face-lp.jpg'),
  bornToDie: require('../assets/images/albums/born-to-die.jpg'),
  comeAroundSundown: require('../assets/images/albums/come-around-sundown.jpg'),
  dearMissLonelyhearts: require('../assets/images/albums/dear-miss-lonelyhearts.jpg'),
  exRe: require('../assets/images/albums/ex-re.jpg'),
  extraMachine: require('../assets/images/albums/extraordinary-machine.jpg'),
  housesOfTheHoly: require('../assets/images/albums/houses-of-the-holy.jpg'),
  illuminate: require('../assets/images/albums/illuminate.jpg'),
  seaOfCowards: require('../assets/images/albums/sea-of-cowards.jpg'),
  stadiumArcadium: require('../assets/images/albums/stadium-arcadium.jpg'),
  swimming: require('../assets/images/albums/swimming.jpg'),
  theCreekDrank: require('../assets/images/albums/the-creek-drank-the-cradle.jpg'),
  theLegendOfMrRager: require('../assets/images/albums/the-legend-of-mr-rager.jpg'),
  theLonesomeCrowdedWest: require('../assets/images/albums/the-lonesome-crowded-west.jpg'),
  whenWeAllFallAsleep: require('../assets/images/albums/when-we-all-fall-asleep.jpg'),
  wishYouWereHere: require('../assets/images/albums/wish-you-where-here.jpg'),
};
